version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medical
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/medical
      JWT_SECRET: supersecret
    depends_on:
      - db
    ports:
      - "3001:3001"

  migrate:
    build: ./backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/medical
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy"

  seed:
    build: ./backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/medical
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && pnpm exec node scripts/seed.js"

volumes:
  db-data:
