services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medical
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: .
    command: pnpm dev
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/medical
      JWT_SECRET: your-super-secret-jwt-key-here-change-in-production
      JWT_EXPIRES_IN: 24h
      JWT_REFRESH_SECRET: your-super-secret-refresh-jwt-key-here-change-in-production
      JWT_REFRESH_EXPIRES_IN: 7d
      NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db
volumes:
  pgdata: 